from pathlib import Path

BASE_DIR     = Path(__file__).parent
PROJECT_DIR  = BASE_DIR.parent
DATA_DIR     = PROJECT_DIR / "data"

# Raster
RASTER_ZIP   = DATA_DIR / "HYP_HR_SR_W_DR.zip"
RASTER_ZIP_ENTRY = "HYP_HR_SR_W_DR.tif"
EXTRACTED_DIR = DATA_DIR / "extracted"
RASTER_COG    = EXTRACTED_DIR / "HYP_HR_SR_W_DR_cog.tif"
RASTER_TIF    = RASTER_COG   # COG with internal overviews — fast tile rendering

# Vector ZIPs
PHYSICAL_ZIP = DATA_DIR / "10m_physical.zip"
TEOW_ZIP     = DATA_DIR / "Terrestrial Ecoregions of the World.zip"
TEOW_SHP     = "data/commondata/data0/wwf_terr_ecos.shp"
# Pre-reprojected WGS84 version (generated by reproject command)
TEOW_WGS84   = EXTRACTED_DIR / "wwf_terr_ecos_wgs84.shp"
# Merged WGS84 with BIOME/REALM_1/area_km2/eco_code — seed source for eco_geo_unit
TEOW_MERGED  = EXTRACTED_DIR / "wwf_terr_ecos_merged.shp"

# Tile cache
TILE_CACHE_SIZE = 512

# CORS origins (Vite dev + production)
PORT = 8001

CORS_ORIGINS = [
    "http://localhost:5173", "http://localhost:4173",
    "http://127.0.0.1:5173", "http://127.0.0.1:4173",
]
